dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r"^tinymce/", include('tinymce.urls')),  # 富文本编辑器
    url(r"^search/", include('haystack.urls')),  # 全文检索框架
    url(r'^user/', include('df_user.urls', namespace='user')),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),
    url(r'^order/', include('df_order.urls', namespace='order')),
    url(r'^', include('df_goods.urls', namespace='goods')),
]

df_cart/urls.py
from django.conf.urls import url
from df_cart import views
urlpatterns = [
    url(r"^add/$", views.cart_add, name="add"),  # 购物车增加选项
    url(r'^$', views.cart_show, name='show'),  # /cart显示购物车页面
    url(r"^count/$", views.cart_count, name='count'),  # 显示购物车总数
    url(r"^update/$", views.cart_update, name="update"),  # 更新
    url(r"^del/$", views.cart_del, name="delete")
]

df_goods/urls.py
from django.conf.urls import url
from df_goods import views

urlpatterns = [
    url(r"^index", views.index, name="index"),  # 网站首页
    url(r"^goods/detail/(?P<goods_id>\d+)/$", views.detail, name="detail"), # /goods/detail/(goods_id) 网站详情页
    url(r"^list/(?P<type_id>\d+)/(?P<page>\d+)/$", views.list, name="list"), # 列表详情
]

df_user/urls.py
from django.conf.urls import url
from df_user import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'), # 用户注册页面
    url(r"^login/$", views.login, name="login"),  # 登录
    url(r"^register_handle/$", views.register_handle, name="register_handle"),  # 注册处理页面
    url(r"^check_user_exist/$", views.check_user_exist, name="check_user_exist"),  # 验证注册的用户名是否已存在
    url(r'^active/(?P<token>.*)/$', views.register_active, name="active"),  # 用户激活视图
    url(r"^login_handle/$", views.login_handle, name="login_handle"),  # 登录验证视图
    url(r"^center/info/$", views.center_info, name="user"),  # 用户中心页
    url(r"^center/order/$", views.center_order, name="order"),
    url(r"^center/site/$", views.center_site, name="address"),
    url(r"^logout/$", views.logout, name="logout")
]

df_goods/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField
from df_goods.enums import *

# Create your models here.
# 10.27 15：25第一次迁移文件生成列表时 报出NoneType object Is not callable 错误 可能是哪个模块导入错误

class GoodsManager(models.Manager):
    '''商品模型管理器类'''
    # sort='new' 按照创建时间进行排序
    # sort='hot' 按照商品销量进行排序
    # sort='price' 按照商品价格进行排序
    # sort 按照默认排序进行查询
    def get_goods_by_type(self, type_id, limit=None, sort='default'):
        '''根据商品的类型id查询商品信息'''
        if sort == 'new':
            order_by = ('-create_time',)
        elif sort == 'hot':
            order_by = ('-sales',)
        elif sort == 'price':
            order_by = ('price',)
        else:
            order_by = ('-pk',)

        # 查询数据
        goods_li = self.filter(type_id=type_id).order_by(*order_by)

        if limit:
            # 限制查询结果集
            goods_li = goods_li[:limit]

        # 返回数据
        return goods_li

    def get_goods_by_id(self, goods_id):
        '''根据商品的id查询商品信息'''
        try:
            goods = Goods.objects.get(id=goods_id)
        except Goods.DoesNotExist:
            # 商品不存在
            goods = None
        return goods


class Goods(BaseModel):
    '''商品模型类'''
    # status_choices = (
    #     (0, '下线商品'),
    #     (1, '上线商品')
    # )

    # goods_type_choices = (
    #     (1, '新鲜水果'),
    #     (2, '海鲜水产'),
    #     (3, '猪牛羊肉'),
    #     (4, '禽类蛋品'),
    #     (5, '新鲜蔬菜'),
    #     (6, '速冻食品')
    # )

    status_choices = ((k,v) for k,v in STATUS_CHOICES.items())
    goods_type_choices = ((k,v) for k,v in GOODS_TYPE.items())

    type_id = models.SmallIntegerField(default=FRUIT, choices=goods_type_choices, verbose_name='商品种类')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=128, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')
    status = models.SmallIntegerField(default=ONLINE, choices=status_choices, verbose_name='商品状态')

    objects = GoodsManager()

    class Meta:
        db_table = 's_goods'


class ImageManager(models.Manager):
    '''商品图片模型管理器类'''
    pass


class GoodsImage(models.Model):
    '''商品图片模型类'''
    goods = models.ForeignKey('Goods', verbose_name='所属商品')
    image = models.ImageField(upload_to='goods', verbose_name='图片路径')

    objects = ImageManager()

    class Meta:
        db_table = 's_goods_image'

df_goods/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from df_goods.models import Goods
from df_goods.enums import *
from django.core.paginator import Paginator
from django_redis import get_redis_connection

# Create your views here.

# /index/
def index(request):
    '''首页视图'''
    # 需要查出每个商品种类销量前四和新品前三的商品
    hotlist = []
    newlist = []
    # 获取到销量列表
    for temp in GOODS_TYPE.keys():
        hotlist.append(Goods.objects.get_goods_by_type(type_id=temp, limit=4, sort="hot"))

    for temp in GOODS_TYPE.keys():
        newlist.append(Goods.objects.get_goods_by_type(type_id=temp, limit=3, sort='new'))

    content = {
        'fruit_hot':hotlist[0],
        'seafood_hot':hotlist[1],
        'meat_hot':hotlist[2],
        'eggs_hot':hotlist[3],
        'vegetables_hot':hotlist[4],
        'frozen_hot':hotlist[5],
        'fruit_new':newlist[0],
        'seafood_new':newlist[1],
        'meat_new':newlist[2],
        'eggs_new':newlist[3],
        'vegetables_new':newlist[4],
        'frozen_new':newlist[5]
        }
    # fruit_hot = Goods.objects.get_goods_by_type(type_id=FRUIT, limit=4, sort='hot')
    # fruit_new = Goods.objects.get_goods_by_type(type_id=FRUIT, limit=3, sort='new')
    return render(request, "df_goods/index.html", content)


# /goods/detail/(goods_id)/
def detail(request, goods_id):
    '''商品详情页'''
    goods = Goods.objects.get_goods_by_id(goods_id=goods_id)
    goods_new = Goods.objects.get_goods_by_type(type_id=goods.type_id, limit=2, sort="new")
    # 设置面包屑导航
    type_title = GOODS_TYPE[goods.type_id]
    if goods is None:
        # 商品不存在
        return redirect(reverse('goods:index'))
    # 每次用户访问详情页后 需要记录历史访问记录
    if request.session.has_key('islogin'):
        con = get_redis_connection('default')  # 连接redis
        # 缓存格式为
        # history_用户id: [1, 2, 3, 4, 5]
        key = 'history_%d'%request.session["user_id"]
        # 从key中移除goods_id
        con.lrem(key, 0, goods_id)
        # 添加goods_id到队首
        con.lpush(key, goods_id)
        # 截取前五个元素
        con.ltrim(key, 0, 4)
    return render(request, "df_goods/detail.html", {"good":goods, "type_title":type_title, "goods_new":goods_new, "type_id": goods.type_id})
# /goods/list/type_id/page/?sort=排序方式
def list(request, type_id, page):
    # 验证type_id
    if int(type_id) not in GOODS_TYPE.keys():
        return redirect(reverse("goods:index"))
    # 根据分类查询商品信息 并排序 如过没有获取到 默认为default
    sort = request.GET.get('sort', "default")

    goods_li = Goods.objects.get_goods_by_type(type_id=type_id, sort=sort)
    # 分页
    paginator = Paginator(goods_li, 10)
    # 获取分页总页数
    num_pages = paginator.num_pages
    # 验证传入的page参数 ~ 为空或大于总页数
    if page == '' or int(page) > num_pages:
        page = 1
    else:
        page = int(page)
    # 获取对应页的内容
    goods_li = paginator.page(page)
    # 处理页码
    # num_pages < 5: 显示所有页码
    # 当前页是前3页: 显示1-5页
    # 当前页是后3页: 显示后5页
    # 其他情况: 显示当前页的前2页，当前页，后两页
    if num_pages < 5:
        pages = range(1, num_pages+1)
    elif page <= 3:
        pages = range(1, 6)
    elif num_pages - page <= 2:
        pages = range(num_pages-4, num_pages+1)
    else:
        pages = range(page-2, page+3)
    # 获取新品推荐
    goods_new = Goods.objects.get_goods_by_type(type_id=type_id, limit=2, sort='new')
    # 面包屑导航
    type_title = GOODS_TYPE[int(type_id)]
    # 定义模板上下文
    context = {
        'goods_li': goods_li,
        'goods_new': goods_new,
        'type_id': type_id,
        'type_title': type_title,
        'sort': sort,
        'pages': pages
    }
    return render(request, "df_goods/list.html", context)

templates/df_goods/detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-商品详情</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script>
$(function () {
		update_total_price()
		// 计算商品的总价
		function  update_total_price() {
				// 获取商品的数量和价格
				goods_price = $('.show_pirze').children('em').text()
				goods_count = $('.num_show').val()
				// 计算商品的总价
				goods_price = parseFloat(goods_price)
				goods_count = parseInt(goods_count)
				total_price = goods_price*goods_count
				// 重新设置商品总价
				$('.total').children('em').text(total_price.toFixed(2)+'元')
		}

		// 商品增加
		$('.add').click(function () {
				// 获取商品的数量
				goods_count = $('.num_show').val()
				// 加1
				goods_count = parseInt(goods_count)+1
				// 重新设置商品数目
				$('.num_show').val(goods_count)
				// 更新总价
				update_total_price()
		})

		// 商品减少
		$('.minus').click(function () {
				// 获取商品的数量
				goods_count = $('.num_show').val()

				// 加1
				goods_count = parseInt(goods_count)-1
				if (goods_count == 0){
						goods_count = 1
				}

				// 重新设置商品数目
				$('.num_show').val(goods_count)

				// 更新总价
				update_total_price()
		})

		// 手动输入
		$('.num_show').blur(function () {
				// 获取商品的数量
				goods_count = $('.num_show').val()
				// 校验数据
				if (isNaN(goods_count) || goods_count.trim().length == 0 || parseInt(goods_count) <= 0) {
						goods_count = 1
				}
				// 重新设置商品数目
				$('.num_show').val(parseInt(goods_count))

				// 更新总价
				update_total_price()
		})
})
</script>

</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.islogin %}
					<div class="login_btn fl">
						欢迎您：<em>{{ request.session.username }}</em>
						<span>|</span>
						<a href="{% url 'user:logout' %}">退出</a>
					</div>
				{% else %}
					<div class="login_btn fl">
						<a href="{% url 'user:login' %}">登录</a>
						<span>|</span>
						<a href="{% url 'user:register' %}">注册</a>
					</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src='{% static "images/logo.png" %}'></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/list/1/1/" class="fruit">新鲜水果</a></li>
					<li><a href="/list/2/1/" class="seafood">海鲜水产</a></li>
					<li><a href="/list/3/1/" class="meet">猪牛羊肉</a></li>
					<li><a href="/list/4/1/" class="egg">禽类蛋品</a></li>
					<li><a href="/list/5/1/" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="/list/6/1/" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<div class="breadcrumb">
			<a href="{% url 'goods:index' %}">全部分类</a>
			<span>></span>
			<a href="{% url 'goods:list' type_id=type_id page=1 %}">{{ type_title }}</a>
		</div>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{% static good.image %}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ good.name }}</h3>
			<p>{{ good.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ good.price }}</em></span>
				<span class="show_unit">单  位：{{ good.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>16.80元</em></div>
			<div class="operate_btn">
				{% csrf_token %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" goods_id="{{ good.id }}" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for goods in goods_new %}
					<li>
						<a href="/goods/detail/{{ goods.id }}"><img src="{% static goods.image %}"></a>
						<h4><a href="#">{{ goods.name }}</a></h4>
						<div class="prize">￥{{ goods.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ good.detail|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<div class="add_jump"></div>

	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$.get('{% url "cart:count" %}', function(data){
							// {'res':商品总数}
							$('#show_count').html(data.res)
					 })

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			// 发起ajax请求提交订单
			goods_count = $('.num_show').val();
			goods_id = $(this).attr('goods_id');
			console.log(goods_count, goods_id);
			csrf = $('input[name="csrfmiddlewaretoken"]').val()
			params = {
				'goods_count':goods_count,
				'goods_id':goods_id,
				'csrfmiddlewaretoken':csrf
			}
			$.post("{% url 'cart:add' %}", params, function(data) {
				/*optional stuff to do after success */
				if(data.res == 5){
					$(".add_jump").stop().animate({
						'left':
						$to_y+7,
						'top': $to_x+7},
						"fast", function() {
							$(".add_jump").fadeOut('fast',function(){
								count = $('#show_count').html()
                count = parseInt(count)+parseInt(goods_count)
                $('#show_count').html(count);
							});

					});
				}
				else{
					alert(data.errmsg)
				}
			});

		})
	</script>

</body>
</html>

templates/df_goods/list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	{% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-商品列表</title>
	<link rel="stylesheet" type="text/css" href='{% static "css/reset.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'>
	<script type="text/javascript" src='{% static "js/jquery-1.12.4.min.js" %}'></script>
	<script type="text/javascript" src='{% static "js/jquery-ui.min.js" %}'></script>
	<script type="text/javascript" src='{% static "js/slide.js" %}'></script>
	<script type="text/javascript">
	$(document).ready(function() {
		$.get('{% url "cart:count" %}', function(data){
							// {'res':商品总数}
							$('#show_count').html(data.res)
					 })
	});

	</script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.islogin %}
					<div class="login_btn fl">
						欢迎您：<em>{{ request.session.username }}</em>
						<span>|</span>
						<a href="{% url 'user:logout' %}">退出</a>
					</div>
				{% else %}
					<div class="login_btn fl">
						<a href="{% url 'user:login' %}">登录</a>
						<span>|</span>
						<a href="{% url 'user:register' %}">注册</a>
					</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src='{% static "images/logo.png" %}'></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/list/1/1/" class="fruit">新鲜水果</a></li>
					<li><a href="/list/2/1/" class="seafood">海鲜水产</a></li>
					<li><a href="/list/3/1/" class="meet">猪牛羊肉</a></li>
					<li><a href="/list/4/1/" class="egg">禽类蛋品</a></li>
					<li><a href="/list/5/1/" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="/list/6/1/" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<div class="breadcrumb">
			<a href="{% url 'goods:index' %}">全部分类</a>
			<span>></span>
			<a href="{% url 'goods:list' type_id=type_id page=1 %}">{{ type_title }}</a>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for goods in goods_new %}
					<li>
						<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
						<h4><a href="#">{{ goods.name }}</a></h4>
						<div class="prize">￥{{ goods.price }}</div>
					</li>
					{% endfor %}
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="/list/{{ type_id }}/1/" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="/list/{{ type_id }}/1/?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="/list/{{ type_id }}/1/?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for goods in goods_li %}
				<li>
					<a href="{% url 'goods:detail' goods_id=goods.id %}"><img src="{% static goods.image %}"></a>
					<h4><a href="{% url 'goods:detail' goods_id=goods.id %}">{{ goods.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.price }}</span>
						<span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>

			<div class="pagenation">
				{% if goods_li.has_previous %}
				    <a href="/list/{{ type_id }}/{{ goods_li.previous_page_number }}/?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == goods_li.number %}
                        <a href="/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="/list/{{ type_id }}/{{ pindex }}/?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if goods_li.has_next %}
				    <a href="/list/{{ type_id }}/{{ goods_li.next_page_number }}/?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


</body>
</html>