dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r"^tinymce/", include('tinymce.urls')),  # 富文本编辑器
    url(r"^search/", include('haystack.urls')),  # 全文检索框架
    url(r'^user/', include('df_user.urls', namespace='user')),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),
    url(r'^order/', include('df_order.urls', namespace='order')),
    url(r'^', include('df_goods.urls', namespace='goods')),
]

df_cart/urls.py
from django.conf.urls import url
from df_cart import views
urlpatterns = [
    url(r"^add/$", views.cart_add, name="add"),  # 购物车增加选项
    url(r'^$', views.cart_show, name='show'),  # /cart显示购物车页面
    url(r"^count/$", views.cart_count, name='count'),  # 显示购物车总数
    url(r"^update/$", views.cart_update, name="update"),  # 更新
    url(r"^del/$", views.cart_del, name="delete")
]

df_goods/urls.py
from django.conf.urls import url
from df_goods import views

urlpatterns = [
    url(r"^index", views.index, name="index"),  # 网站首页
    url(r"^goods/detail/(?P<goods_id>\d+)/$", views.detail, name="detail"), # /goods/detail/(goods_id) 网站详情页
    url(r"^list/(?P<type_id>\d+)/(?P<page>\d+)/$", views.list, name="list"), # 列表详情
]

df_order/urls.py
from django.conf.urls import url
from df_order import views

urlpatterns = [
    url(r"^place/$", views.order_place, name="place"),  # 显示订单提交页面
    url(r"^handle/$", views.order_handle, name="handle")  # ajax提交订单接口
]

df_user/urls.py
from django.conf.urls import url
from df_user import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'), # 用户注册页面
    url(r"^login/$", views.login, name="login"),  # 登录
    url(r"^register_handle/$", views.register_handle, name="register_handle"),  # 注册处理页面
    url(r"^check_user_exist/$", views.check_user_exist, name="check_user_exist"),  # 验证注册的用户名是否已存在
    url(r'^active/(?P<token>.*)/$', views.register_active, name="active"),  # 用户激活视图
    url(r"^login_handle/$", views.login_handle, name="login_handle"),  # 登录验证视图
    url(r"^center/info/$", views.center_info, name="user"),  # 用户中心页
    url(r"^center/order/$", views.center_order, name="order"),
    url(r"^center/site/$", views.center_site, name="address"),
    url(r"^logout/$", views.logout, name="logout")
]

df_cart/models.py
from django.db import models

# Create your models here.

df_cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django_redis import get_redis_connection
from df_goods.models import Goods
from utils.decorators import login_required
# Create your views here.

#/cart/add
def cart_add(request):
    '''post 提交到购物车'''
    # 登录判断 ajax请求不能用装饰器 因为无法跳转
    # 传入商品id 购买个数
    goods_id = request.POST.get('goods_id')
    count = request.POST.get('goods_count')
    if not request.session.has_key('islogin'):
        # 用户未登录
        return JsonResponse({'res':0, 'errmsg':'用户未登录'})

    # 判断是否为空
    if not all([goods_id, count]):
        return JsonResponse({'res':1, 'errmsg':'数据为空'})
    # 数据是否在表内
    goods = Goods.objects.get_goods_by_id(goods_id=goods_id)
    if not goods:
        return JsonResponse({'res':2, 'errmsg':'数据不存在'})
    # 转为整数并判断库存
    try:
        count = int(count)
    except Exception as e:
        return JsonResponse({'res':3, 'errmsg':'商品数目非法'})
    # 获取redis连接
    conn = get_redis_connection('default')
    cart_key = 'cart_%d'%request.session.get('user_id')
    res = conn.hget(cart_key, goods_id)
    # 对之前购物车的数据进行累加
    if not res:
        res = count
    else:
        res = count + int(res)
    # 判断库存
    if res > goods.stock:
        return JsonResponse({'res':4, 'errmsg':"商品库存不足"})
    # 保存到缓存中
    conn.hset(cart_key, goods_id, res)
    return JsonResponse({'res':5})

# /count/
def cart_count(request):
    '''获取用户购物车中商品的总数'''
    # 进行登录判断
    if not request.session.has_key('islogin'):
        # 用户未登录
        return JsonResponse({'res': 0})

    # 获取用户购物车中商品的总数
    conn = get_redis_connection('default')
    cart_key = 'cart_%d'%request.session.get('user_id')

    # res = conn.hgetall(cart_key)
    # # print(res)
    # # 遍历计算商品的总数
    # count = 0
    # for i in res.values():
    #     count += int(i)

    res = conn.hvals(cart_key)
    count = 0
    # 遍历每一种商品
    for temp in res:
        count += int(temp)
    return JsonResponse({'res':count})


# /cart
@login_required
def cart_show(request):
    '''购物车页面显示'''
    conn = get_redis_connection('default')
    cart_key = 'cart_%d'%request.session["user_id"]
    res_dict = conn.hgetall(cart_key)
    print(res_dict)

    # 用户购物车中商品的总数
    total_count = 0
    # 所有商品的总价
    total_price = 0
    #
    # # 用户购物车中商品的信息，商品的数目，已经小计
    goods_li = []
    for id,count in res_dict.items():
        # 根据商品id获取商品的信息
        goods = Goods.objects.get_goods_by_id(goods_id=id)
        # 动态给goods增加属性，记录商品的小计
        goods.amount = goods.price*int(count)
        # 动态给goods增加属性count, 记录商品的数目
        goods.count = count
        goods_li.append(goods)

        total_count += int(count)
        total_price += goods.amount

    # 组织模板上下文
    context = {'goods_li':goods_li, 'total_count':total_count,
               'total_price':total_price}

    return render(request, 'df_cart/cart.html', context)
    return render(request, "df_cart/cart.html")

# /cart/update/
def cart_update(request):
    '''更新购物车商品的数目'''
    # 进行登录判断
    if not request.session.has_key('islogin'):
        # 用户未登录
        return JsonResponse({'res': 0, 'errmsg': '请先登录'})

    # 接收数据
    goods_id = request.POST.get('goods_id')
    goods_count = request.POST.get('goods_count')

    # 数据校验
    if not all([goods_id, goods_count]):
        return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

    goods = Goods.objects.get_goods_by_id(goods_id=goods_id)
    if goods is None:
        return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

    try:
        count = int(goods_count)
    except Exception as e:
        return JsonResponse({'res': 3, 'errmsg': '商品数目必须为数字'})

    # 更新购物车商品的数目
    conn = get_redis_connection('default')
    cart_key = 'cart_%d'%request.session.get('user_id')

    # 判断商品的库存
    if count > goods.stock:
        return JsonResponse({'res':4, 'errmsg':'商品库存不足'})

    # 更新操作
    conn.hset(cart_key, goods_id, count)
    return JsonResponse({'res':5})

# /cart/del/
def cart_del(request):
    '''商品用户购物车记录'''
    # 进行登录判断
    if not request.session.has_key('islogin'):
        # 用户未登录
        return JsonResponse({'res': 0, 'errmsg': '请先登录'})

    # 接收数据
    goods_id = request.POST.get('goods_id')

    # 进行校验
    if not all([goods_id]):
        return JsonResponse({'res':1, 'errmsg':'数目不完整'})

    goods = Goods.objects.get_goods_by_id(goods_id=goods_id)
    if goods is None:
        return JsonResponse({'res':2, 'errmsg':'商品不存在'})

    # 删除redis中对应的记录
    conn = get_redis_connection('default')
    cart_key = 'cart_%d'%request.session.get('user_id')

    conn.hdel(cart_key, goods_id)

    # 返回结果
    return JsonResponse({'res':3})

templates/df_cart/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	{% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-购物车</title>
	<link rel="stylesheet" type="text/css" href='{% static "css/reset.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'>
	<script type="text/javascript" src='{% static "js/jquery-1.12.4.min.js" %}'></script>
	<script>
    $(function () {
        // 计算所有被选中的商品的总数目和总价格
        function update_goods_info() {
            total_count = 0
            total_price = 0
            // 获取所有被选中的商品所在的ul元素
            $('.cart_list_td').find(':checked').parents('ul').each(function () {
                // 计算商品的小计
                res_dict = update_goods_amount($(this))

                // 累计
                total_count += res_dict.goods_count
                total_price += res_dict.goods_amount
            })

            // 设置商品的总价和总数目
            $('.settlements').find('em').text(total_price.toFixed(2))
            $('.settlements').find('b').text(total_count)
        }

        // 计算商品的小计
        function update_goods_amount(goods_ul) {
            // 获取商品的价格和数量
            goods_price = goods_ul.children('.col05').text()
            goods_count = goods_ul.find('.num_show').val()
            // 计算商品的小计
            goods_price = parseFloat(goods_price)
            goods_count = parseFloat(goods_count)
            goods_amount = goods_price*goods_count
            // 设置商品小计
            goods_ul.children('.col07').text(goods_amount.toFixed(2)+'元')

            return {'goods_count':goods_count, 'goods_amount':goods_amount}
        }

        // 全选和全不选
        $('.settlements').find(':checkbox').change(function () {
            // 获取全选checkbox的选中状态
            is_checked = $(this).prop('checked')
            // 遍历所有商品的checkbox,设置选中状态和全选checkbox一致
            $('.cart_list_td').find(':checkbox').each(function () {
                $(this).prop('checked', is_checked)
            })

            // 更新选中的商品总数目和总价格
            update_goods_info()
        })

        // 商品的checkbox选中状态发生改变时，全选checkbox的发生改变
        $('.cart_list_td').find(':checkbox').change(function () {
            // 获取所有商品的checkbox的数目
            all_len = $('.cart_list_td').find(':checkbox').length
            // 获取所有被选中的商品checkbox数目
            checked_len = $('.cart_list_td').find(':checked').length
            if (checked_len < all_len){
                $('.settlements').find(':checkbox').prop('checked', false)
            }
            else {
                $('.settlements').find(':checkbox').prop('checked', true)
            }

            // 更新选中的商品总数目和总价格
            update_goods_info()

        })

        // 进行购物车商品数目的更新
        error_update = false
        function update_remote_cart_info(goods_id, goods_count) {
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 请求/cart/update/, 进行购物车商品数目更新
            params = {'goods_id':goods_id, 'goods_count':goods_count,
                    'csrfmiddlewaretoken':csrf}
            // 设置同步
            $.ajaxSettings.async = false
            $.post('/cart/update/', params, function (data) {
                if (data.res == 5){
                    // alert('更新成功')
                    error_update = false
                }
                else{
                    error_update = true
                    alert(data.errmsg)
                }
            })
            // 设置异步
            $.ajaxSettings.async = true
        }

        // 更新页面商品购物车商品的总数
        function update_cart_count() {
            $.get('/cart/count/', function (data) {
                $('.total_count').children('em').text(data.res)
            })
        }

        // 购物车商品数目的增加
        $('.add').click(function () {
            // 获取商品的id和商品的数目
            goods_id = $(this).next().attr('goods_id')
            goods_count = $(this).next().val()

            // 发起请求，进行更新操作
            goods_count = parseInt(goods_count)+1
            update_remote_cart_info(goods_id, goods_count)

            // 根据更新的结果进行操作
            if (error_update == false){
                // 更新商品数目
                $(this).next().val(goods_count)
                // 更新成功
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                if (is_checked){
                    // 更新商品的总数目和总价格
                    update_goods_info()
                }
                else{
                    // 更新商品的小计
                    update_goods_amount($(this).parents('ul'))
                }
                // 更新页面上购物车商品的总数
                update_cart_count()
            }

        })

        // 购物车商品数目的减少
        $('.minus').click(function () {
            // 获取商品的id和商品的数目
            goods_id = $(this).prev().attr('goods_id')
            goods_count = $(this).prev().val()

            // 发起请求，进行更新操作
            goods_count = parseInt(goods_count)-1
            if (goods_count <= 0){
                goods_count = 1
            }

            update_remote_cart_info(goods_id, goods_count)

            // 根据更新的结果进行操作
            if (error_update == false){
                // 更新商品数目
                $(this).prev().val(goods_count)
                // 更新成功
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                if (is_checked){
                    // 更新商品的总数目和总价格
                    update_goods_info()
                }
                else{
                    // 更新商品的小计
                    update_goods_amount($(this).parents('ul'))
                }
                // 更新页面上购物车商品的总数
                update_cart_count()
            }
        })

        // 记录用户输入之前购物车商品数目
        pre_goods_count = 0
        $('.num_show').focus(function () {
            pre_goods_count = $(this).val()
        })

        // 购物车商品数目的手动输入
        $('.num_show').blur(function () {
            // 获取商品的id和商品的数目
            goods_id = $(this).attr('goods_id')
            goods_count = $(this).val()

            // 发起请求，进行更新操作
            // 校验用户的输入的数据
            if (isNaN(goods_count) || goods_count.trim().length==0 || parseInt(goods_count)<=0){
                // 显示用户输入之前购物车商品的数目
                $(this).val(pre_goods_count)
                return
            }

            goods_count = parseInt(goods_count)
            update_remote_cart_info(goods_id, goods_count)

            // 根据更新的结果进行操作
            if (error_update == false){
                // 更新商品数目
                $(this).val(goods_count)
                // 更新成功
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
                if (is_checked){
                    // 更新商品的总数目和总价格
                    update_goods_info()
                }
                else{
                    // 更新商品的小计
                    update_goods_amount($(this).parents('ul'))
                }
                // 更新页面上购物车商品的总数
                update_cart_count()
            }
            else{
                $(this).val(pre_goods_count)
            }
        })

        // 删除用户购物车数据
        $('.cart_list_td').children('.col08').children('a').click(function () {
            // 获取商品的id
            goods_ul = $(this).parents('ul')
            goods_id = $(this).parents('ul').find('.num_show').attr('goods_id')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 发起请求，访问/cart/del/地址，删除购物车记录
            params = {'goods_id':goods_id, 'csrfmiddlewaretoken':csrf}
            $.post('/cart/del/', params, function (data) {
                if (data.res == 3){
                    // 删除成功
                    // 删除自身及其子元素 empty:删除子元素
                    goods_ul.fadeOut()
                    // 获取goods_ul中checkbox的选中状态
                    is_checked = goods_ul.find(':checkbox').prop('checked')
                    if (is_checked){
                        // 更新选中商品的总数目和总价格
                        update_goods_info()
                    }
                    // 更新页面上购物车商品的总数
                    update_cart_count()
                }
                else {
                    alert(data.errmsg)
                }
            })
        })
    })
    </script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.islogin %}
					<div class="login_btn fl">
						欢迎您：<em>{{ request.session.username }}</em>
						<span>|</span>
						<a href="{% url 'user:logout' %}">退出</a>
					</div>
				{% else %}
					<div class="login_btn fl">
						<a href="{% url 'user:login' %}">登录</a>
						<span>|</span>
						<a href="{% url 'user:register' %}">注册</a>
					</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static "images/logo.png" %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
		<ul class="cart_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
			<li class="col06">操作</li>
		</ul>
		<form method="post" action="{%url 'order:place'%}">
	{% for goods in goods_li %}
<ul class="cart_list_td clearfix">
	<li class="col01"><input type="checkbox" name="goods_ids" value="{{ goods.id }}" checked></li>
	<li class="col02"><img src="{% static goods.image %}"></li>
	<li class="col03">{{ goods.name }}<br><em>{{ goods.price }}元/{{ goods.unite }}</em></li>
	<li class="col04">{{ goods.unite }}</li>
	<li class="col05">{{ goods.price }}元</li>
	<li class="col06">
		<div class="num_add">
			<a href="javascript:;" class="add fl">+</a>
			<input type="text" goods_id="{{ goods.id }}" class="num_show fl" value="{{ goods.count }}">
			<a href="javascript:;" class="minus fl">-</a>
		</div>
	</li>
	<li class="col07">{{ goods.amount }}元</li>
	<li class="col08"><a href="javascript:;">删除</a></li>
</ul>
	{% endfor %}



	<ul class="settlements">
			{% csrf_token %}
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
		</form>
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>