dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r"^tinymce/", include('tinymce.urls')),  # 富文本编辑器
    url(r"^search/", include('haystack.urls')),  # 全文检索框架
    url(r'^user/', include('df_user.urls', namespace='user')),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),
    url(r'^order/', include('df_order.urls', namespace='order')),
    url(r'^', include('df_goods.urls', namespace='goods')),
]

df_cart/urls.py
from django.conf.urls import url
from df_cart import views
urlpatterns = [
    url(r"^add/$", views.cart_add, name="add"),  # 购物车增加选项
    url(r'^$', views.cart_show, name='show'),  # /cart显示购物车页面
    url(r"^count/$", views.cart_count, name='count'),  # 显示购物车总数
    url(r"^update/$", views.cart_update, name="update"),  # 更新
    url(r"^del/$", views.cart_del, name="delete")
]

df_goods/urls.py
from django.conf.urls import url
from df_goods import views

urlpatterns = [
    url(r"^index", views.index, name="index"),  # 网站首页
    url(r"^goods/detail/(?P<goods_id>\d+)/$", views.detail, name="detail"), # /goods/detail/(goods_id) 网站详情页
    url(r"^list/(?P<type_id>\d+)/(?P<page>\d+)/$", views.list, name="list"), # 列表详情
]

df_order/urls.py
from django.conf.urls import url
from df_order import views

urlpatterns = [
    url(r"^place/$", views.order_place, name="place"),  # 显示订单提交页面
    url(r"^handle/$", views.order_handle, name="handle")  # ajax提交订单接口
]

df_user/urls.py
from django.conf.urls import url
from df_user import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'), # 用户注册页面
    url(r"^login/$", views.login, name="login"),  # 登录
    url(r"^register_handle/$", views.register_handle, name="register_handle"),  # 注册处理页面
    url(r"^check_user_exist/$", views.check_user_exist, name="check_user_exist"),  # 验证注册的用户名是否已存在
    url(r'^active/(?P<token>.*)/$', views.register_active, name="active"),  # 用户激活视图
    url(r"^login_handle/$", views.login_handle, name="login_handle"),  # 登录验证视图
    url(r"^center/info/$", views.center_info, name="user"),  # 用户中心页
    url(r"^center/order/$", views.center_order, name="order"),
    url(r"^center/site/$", views.center_site, name="address"),
    url(r"^logout/$", views.logout, name="logout")
]

df_order/models.py
from django.db import models
from db.base_model import BaseModel
from df_user.models import PassportInfo
# from df_goods.models import Goods
# Create your models here.
class OrderInfoManager(models.Manager):
    "订单信息模型管理器类"
    def get_order_by_id(self, user_id):
        try:
            orders_li = self.filter(passport_id=user_id)
            return orders_li
        except Exception as e:
            print(e)

    # def save_order_info(self, passport_id, pay_method, goods_ids):
    #     goods_ids = goods_ids.split(",")
    #     order = self.create(
    #         passport_id = passport_id,
    #         pay_method = pay_method,
    #
    #     )



class OrderInfo(BaseModel):
    "订单信息模型类"

    PAY_METHOD_CHOICES = (
        (1, "货到付款"),
        (2, "微信支付"),
        (3, "支付宝"),
        (4, "银联支付")
    )

    PAY_METHODS_ENUM = {
        "CASH": 1,
        "WEIXIN": 2,
        "ALIPAY": 3,
        "UNIONPAY": 4,
    }

    ORDER_STATUS_CHOICES = (
        (1, "待支付"),
        (2, "待发货"),
        (3, "待收货"),
        (4, "待评价"),
        (5, "已完成"),
    )

    order_id = models.CharField(max_length=64, primary_key=True, verbose_name="订单编号")
    passport = models.ForeignKey("df_user.Passport", verbose_name="下单账户")
    addr = models.ForeignKey("df_user.PassportInfo", verbose_name="收货地址")
    total_count = models.IntegerField(default=1, verbose_name="商品总数")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="商品总价")
    transit_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="运费")
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=1, verbose_name="支付方式")
    status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name="订单状态")
    trade_id = models.CharField(max_length=100, unique=True, null=True, blank=True, verbose_name="支付编号")
    objects = OrderInfoManager()

    class Meta:
        db_table = "s_order_info"

class OrderGoodsManager(models.Manager):
    def save_order_goods(self):
        pass

    def get_order_goods_by_order_id(self, order_id):
        order_li = self.filter(order_id=order_id)
        return order_li

class OrderGoods(BaseModel):
    "订单商品模型类"
    order = models.ForeignKey("OrderInfo", verbose_name="所属订单")
    goods = models.ForeignKey("df_goods.Goods", verbose_name="订单商品")
    count = models.IntegerField(default=1, verbose_name="商品数量")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="商品价格")
    objects = OrderGoodsManager()

    class Meta:
        db_table = "s_order_goods"

df_order/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from utils.decorators import login_required
from df_user.models import PassportInfo
from df_goods.models import Goods
from df_order.models import OrderGoods, OrderInfo
from django_redis import get_redis_connection
from django.http import JsonResponse
from django.db import transaction
from datetime import datetime
# Create your views here.

# /order/place/
@login_required
def order_place(request):
    "显示地址订单页"
    goods_ids = request.POST.getlist("goods_ids")
    print(goods_ids)
    if not all(goods_ids):
        # 数据不完整则跳转回购物车页面
        return redirect(reverse("cart:show"))
    # 获取登录用户的id
    user_id = request.session.get("user_id")
    # 查询用户默认的收货地址
    passport_info = PassportInfo.objects.get_address(passport_id=user_id)

    # 商品的总数目，总金额
    total_count = 0
    total_price = 0
    goods_li =list()

    conn = get_redis_connection('default')
    cart_key = "cart_%d" % user_id
    # 用户所要购买的商品信息，数目，和小计
    for temp in goods_ids:
        # 根据商品id获取商品信息
        goods = Goods.objects.get_goods_by_id(goods_id=temp)
        # redis服务器中获取id对应的商品的数目
        count = conn.hget(cart_key, temp)
        goods.count = count
        # 计算商品的小计
        amount = int(count)*goods.price
        goods.amount = amount
        goods_li.append(goods)
        total_count += int(count)
        total_price += amount

    # 运费 需要修改 这里全部设为10元
    transit_price = 10
    # 实际付款
    total_pay = total_price + transit_price
    # 模板上下文
    context = {
        "passport_info": passport_info,
        "goods_li": goods_li,
        "total_count": total_count,
        "total_price": total_price,
        "total_pay": total_pay,
        "goods_ids": goods_ids,
        "transit_price": transit_price
    }
    return render(request, "df_order/place_order.html", context=context)

# 创建订单时候
# 订单信息表(s_order_info)中插入信息: 1条信息
# 订单商品表(s_order_goods)中插入信息: 订单买了多少个商品，插入几条信息


# 用户点击提交订单的时候, 需要发送的数据:
# 1.收货地址 2.支付方式 3.用户所要购买的商品id

# 订单生成的过程:要成功都成功，要失败都失败
# 事务: 原子性:要么成功，要么回滚
# mysql
# 开启事务: begin;
# 事务回滚: rollback;
# 设置事务保存点: savepoint 保存点;
# 回滚到某一个保存点: rollback to 保存点。
# 事务提交: commit;

# 放在事务中
    # 1.向s_order_info添加一条记录
    # 2.遍历项s_order_goods添加记录
        # 2.1 增加商品销量，减少库存
        # 2.2 累计计算商品的总数目和总金额
    # 3. 更新s_order_info对应数据的总数目和总金额
# 4. 清除购物车对应数据
# /order/handle/
# @login_required 由于是ajax请求 无法使用此装饰器跳转

	# "addr_id": addr_id,
	# "pay_method": pay_method,
	# "goods_id": goods_id,
	# "csrfmiddlewaretoken": csrf
@transaction.atomic
def order_handle(request):
    "订单生成处理"
    # 判断用户是否存在
    if not request.session.has_key("user_id"):
        return JsonResponse({
            "res": 0,
            "errmsg": "用户未登录"
    })
    addr_id = request.POST.get("addr_id")
    pay_method = request.POST.get("pay_method")
    goods_ids = request.POST.get("goods_ids")
    print(addr_id, pay_method, goods_ids)
    # 校验数据
    if not all([addr_id, pay_method, goods_ids]):
        return JsonResponse({
            "res": 1,
            "errmsg": "数据不完整"
    })
    try:
        addr = PassportInfo.objects.get(id=addr_id)
    except Exception as e:
        return JsonResponse({
            "res": 2,
            "errmsg": "地址信息错误"
    })

    if int(pay_method) not in OrderInfo.PAY_METHODS_ENUM.values():
        return JsonResponse({
            "res": 3,
            "errmsg": "不支持的支付方式"
    })

    # 生成订单
    user_id = request.session.get("user_id")
    utime = datetime.now().strftime("%Y%m%d%H%M%S")
    order_id = utime + str(user_id)

    # 订单运费
    transit_price = 10
    # 商品总数目，总金额
    total_count = 0
    total_price = 0
    # 事务保存点
    sid = transaction.savepoint()

    conn = get_redis_connection("default")
    # goods_ids = goods_ids.split(",")
    cart_key = "cart_%d" % user_id
    print(goods_ids, cart_key)
    print("123456")
    try:
        # 向订单信息表添加记录
        print("123456")
        order = OrderInfo.objects.create(
            order_id=order_id,
            passport_id=user_id,
            addr_id=addr_id,
            total_count=total_count,
            total_price=total_price,
            transit_price=transit_price,
            pay_method=pay_method
        )
        print(type(goods_ids))

        # 遍历goods_ids
        for id in eval(goods_ids):
            # 根据商品的id获取每一个商品的信息

            goods = Goods.objects.get_goods_by_id(goods_id=int(id))
            if goods is None:
                transaction.savepoint_rollback(sid)
                return JsonResponse({
                    "res": 4,
                    "errmsg": "商品信息错误"
            })
            count = conn.hget(cart_key, id)
            print(count)
            print("*"*20)
            # 判断商品库存
            if int(count) > goods.stock:
                transaction.savepoint_rollback(sid)
                return JsonResponse({
                    "res": 5,
                    "errmsg": "库存不足"
            })
            # 向订单商品表中添加记录
            OrderGoods.objects.create(
                order_id=order_id,
                goods_id=goods.id,
                count=count,
                price=goods.price
            )
            goods.sales += int(count)
            goods.stock -= int(count)
            goods.save()
            # print("goods%d,save") %goods.id
            # 累加商品总价和总数
            total_count += int(count)
            total_price += int(count)*goods.price
        # 更新订单信息中商品的总数目和总金额
        order.total_count = total_count
        order.total_price = total_price
        order.save()
    except Exception as e:
        print (e)
        transaction.savepoint_rollback(sid)
        return JsonResponse({"res": 7, "errmsg": "订单提交失败"})
    # 清除redis数据库中的购物车信息
    print("*"*30)
    print(cart_key)
    conn.hdel(cart_key, *eval(goods_ids))
    print("+"*30)
    # 提交事务
    transaction.savepoint_commit(sid)
    return JsonResponse({"res": 6, "next_url": reverse("user:order")})

templates/df_order/place_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
	{% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-提交订单</title>
	<link rel="stylesheet" type="text/css" href='{% static "css/reset.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'>
	<!-- <script type="text/javascript" src='{% static "js/jquery-1.12.4.min.js" %}'></script> -->
</head>

<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.islogin %}
				<div class="login_btn fl">
					欢迎您：<em>{{ request.session.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>

		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static "images/logo.png" %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="passport_info_id" value="{{ passport_info.id }}" checked="">{{passport_info.addr}} （{{passport_info.name}} 收） {{passport_info.phone}}</dd>
		</dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value="1" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
		{% for goods in goods_li %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{% static goods.image %}"></li>
			<li class="col03">{{ goods.name }}</li>
			<li class="col04">{{ goods.unite }}</li>
			<li class="col05">{{ goods.price }}元</li>
			<li class="col06">{{ goods.count }}</li>
			<li class="col07">{{ goods.amount }}元</li>
		</ul>
		{% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		{% csrf_token %} {# 给提交订单a标签增加一个属性goods_ids, 记录用户要购买的商品的id #}
		<a href="javascript:;" goods_ids="{{ goods_ids }}" id="order_btn">提交订单</a>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888 京ICP备*******8号</p>
	</div>

	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>
	<script type="text/javascript" src='{% static "js/jquery-1.12.4.min.js" %}'></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			// 获取收获地址， 支付方式， 用户购物的商品id
			addr_id = $("input[name='passport_info_id']").val()
			pay_method = $('input[name="pay_style"]:checked').val()
			goods_ids = $(this).attr('goods_ids');
			csrf = $('input[name="csrfmiddlewaretoken"]').val()

			params = {
				"addr_id": addr_id,
				"pay_method": pay_method,
				"goods_ids": goods_ids,
				"csrfmiddlewaretoken": csrf
			}
			$.post('/order/handle/', params, function(data) {
				if (data.res == 6) {
					// 订单创建成功
					localStorage.setItem('order_finish', 2);
					$('.popup_con').fadeIn('fast', function() {

						setTimeout(function() {
							$('.popup_con').fadeOut('fast', function() {
								window.location.href = data.next_url;
							});
						}, 3000)

					});
				}
				else{
					alert(data.errmsg)
				}
				/*optional stuff to do after success */
			});

		});
	</script>
</body>

</html>