dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r"^tinymce/", include('tinymce.urls')),  # 富文本编辑器
    url(r"^search/", include('haystack.urls')),  # 全文检索框架
    url(r'^user/', include('df_user.urls', namespace='user')),
    url(r'^cart/', include('df_cart.urls', namespace='cart')),
    url(r'^order/', include('df_order.urls', namespace='order')),
    url(r'^', include('df_goods.urls', namespace='goods')),
]

df_cart/urls.py
from django.conf.urls import url
from df_cart import views
urlpatterns = [
    url(r"^add/$", views.cart_add, name="add"),  # 购物车增加选项
    url(r'^$', views.cart_show, name='show'),  # /cart显示购物车页面
    url(r"^count/$", views.cart_count, name='count'),  # 显示购物车总数
    url(r"^update/$", views.cart_update, name="update"),  # 更新
    url(r"^del/$", views.cart_del, name="delete")
]

df_goods/urls.py
from django.conf.urls import url
from df_goods import views

urlpatterns = [
    url(r"^index", views.index, name="index"),  # 网站首页
    url(r"^goods/detail/(?P<goods_id>\d+)/$", views.detail, name="detail"), # /goods/detail/(goods_id) 网站详情页
    url(r"^list/(?P<type_id>\d+)/(?P<page>\d+)/$", views.list, name="list"), # 列表详情
]

df_user/urls.py
from django.conf.urls import url
from df_user import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'), # 用户注册页面
    url(r"^login/$", views.login, name="login"),  # 登录
    url(r"^register_handle/$", views.register_handle, name="register_handle"),  # 注册处理页面
    url(r"^check_user_exist/$", views.check_user_exist, name="check_user_exist"),  # 验证注册的用户名是否已存在
    url(r'^active/(?P<token>.*)/$', views.register_active, name="active"),  # 用户激活视图
    url(r"^login_handle/$", views.login_handle, name="login_handle"),  # 登录验证视图
    url(r"^center/info/$", views.center_info, name="user"),  # 用户中心页
    url(r"^center/order/$", views.center_order, name="order"),
    url(r"^center/site/$", views.center_site, name="address"),
    url(r"^logout/$", views.logout, name="logout")
]

templates/search/search.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	{% load staticfiles %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-搜索页</title>
	<link rel="stylesheet" type="text/css" href='{% static "css/reset.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'>
	<script type="text/javascript" src='{% static "js/jquery-1.12.4.min.js" %}'></script>
	<script type="text/javascript" src='{% static "js/jquery-ui.min.js" %}'></script>
	<script type="text/javascript" src='{% static "js/slide.js" %}'></script>
	<script type="text/javascript">
	$(document).ready(function() {
		$.get('{% url "cart:count" %}', function(data){
							// {'res':商品总数}
							$('#show_count').html(data.res)
					 })
	});

	</script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.islogin %}
					<div class="login_btn fl">
						欢迎您：<em>{{ request.session.username }}</em>
						<span>|</span>
						<a href="{% url 'user:logout' %}">退出</a>
					</div>
				{% else %}
					<div class="login_btn fl">
						<a href="{% url 'user:login' %}">登录</a>
						<span>|</span>
						<a href="{% url 'user:register' %}">注册</a>
					</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src='{% static "images/logo.png" %}'></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="/list/1/1/" class="fruit">新鲜水果</a></li>
					<li><a href="/list/2/1/" class="seafood">海鲜水产</a></li>
					<li><a href="/list/3/1/" class="meet">猪牛羊肉</a></li>
					<li><a href="/list/4/1/" class="egg">禽类蛋品</a></li>
					<li><a href="/list/5/1/" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="/list/6/1/" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">{{ query }}</a>
		<span>></span>
		<a href="#">搜索结果:</a>
	</div>

	<div class="main_wrap clearfix">
			<ul class="goods_type_list clearfix">
        {% for item in page %}
				<li>
					<a href="{% url 'goods:detail' goods_id=item.object.id %}"><img src="{% static item.object.image %}"></a>
					<h4><a href="{% url 'goods:detail' goods_id=item.object.id %}">{{ item.object.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ item.object.price }}</span>
						<span class="unit">{{ item.object.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
        {% endfor %}
			</ul>
			<div class="pagenation">
				{% if page.has_previous %}
				    <a href="/search/?q={{ query }}&page={{ page.previous_page_number }}"><上一页</a>
                {% endif %}
                {% for pindex in paginator.page_range %}
									{% if pindex == page.number %}
                    <a href="/search/?q={{ query }}&page={{ pindex }}" class="active">{{ pindex }}</a>
                  {% else %}
                    <a href="/search/?q={{ query }}&page={{ pindex }}">{{ pindex }}</a>
                  {% endif %}
                {% endfor %}
                {% if page.has_next %}
								<a href="/search/?q={{ query }}&page={{ page.next_page_number }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


</body>
</html>